import { InputComponent } from './InputComponent';
import { TimeComponent } from './TimeComponent';
import { PositionComponent } from './PositionComponent';
import { RotationComponent } from './RotationComponent';
import { PrevPositionComponent } from './PrevPositionComponent';
import { GravityForceComponent } from './GravityForceComponent';
import { PullingForceComponent } from './PullingForceComponent';
import { MassComponent } from './MassComponent';
import { AccelerationComponent } from './AccelerationComponent';
import { IterationComponent } from './IterationComponent';
import { PlayerComponent } from './PlayerComponent';
import { ModelComponent } from './ModelComponent';
import { CameraAtComponent } from './CameraAtComponent';
import { BoundariesComponent } from './BoundariesComponent';
import { CollisionComponent } from './CollisionComponent';
import { StaticComponent } from './StaticComponent';
import { AsteroidComponent } from './AsteroidComponent';
import { JumpComponent } from './JumpComponent';
import { TurretComponent } from './TurretComponent';
import { TimerComponent } from './TimerComponent';
import { GravityBehaviourComponent } from './GravityBehaviourComponent';
import { MaxSpeedComponent } from './MaxSpeedComponent';
import { MapComponent } from './MapComponent';
import { MapDependentComponent } from './MapDependentComponent';
import { GravityGunComponent } from './GravityGunComponent';
import { SpaceshipComponent } from './SpaceshipComponent';
import { QuestComponent } from './QuestComponent';
import { MinimapComponent } from './MinimapComponent';
import { BulletComponent } from './BulletComponent';
import { ChildComponent } from './ChildComponent';
import { EffectsComponent } from './EffectsComponent';

export interface ComponentsRegistry {
  rotation: RotationComponent;
  position: PositionComponent;
  prevPosition: PrevPositionComponent;
  gravityForce: GravityForceComponent;
  pullingForce: PullingForceComponent;
  mass: MassComponent;
  acceleration: AccelerationComponent;
  iteration: IterationComponent;
  input: InputComponent;
  player: PlayerComponent;
  model: ModelComponent;
  cameraAt: CameraAtComponent;
  time: TimeComponent;
  boundaries: BoundariesComponent;
  collision: CollisionComponent;
  static: StaticComponent;
  asteroid: AsteroidComponent;
  jump: JumpComponent;
  turret: TurretComponent;
  timer: TimerComponent;
  gravityBehaviour: GravityBehaviourComponent;
  maxSpeed: MaxSpeedComponent;
  map: MapComponent;
  mapDependent: MapDependentComponent;
  gravityGun: GravityGunComponent;
  spaceship: SpaceshipComponent;
  quest: QuestComponent;
  onMinimap: MinimapComponent;
  bullet: BulletComponent;
  child: ChildComponent;
  effects: EffectsComponent;
}

export type ComponentValue<Cmp extends keyof CmpRegistry, CmpRegistry> = CmpRegistry[Cmp];
